version: "3.0"
services:
  db-backend:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bdsm
    ports:
      - 3305:3306
    command: mysqld --lower_case_table_names=1 --sql_mode='' --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --bind-address=0.0.0.0
  backend:
    depends_on:
      - db-backend
    image: haitranquangofficial/buda:backend
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-backend:3306/bdsm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    stdin_open: true
    tty: true
volumes:
  db: